### ISSUE TITLE
File Request.js does not exist: Failed to execute goal com.google.code.maven-replacer-plugin:replacer:1.5.2:replace (default) on project GoogleFrontend: File '/home/usr/greennav/GoogleFrontend/src/main/webapp/js/proc/Request.js' does not exist

### ISSUE THREAD

**Issue by dimplekp** [Greennav/greennav#9]
I tried running _mvn install -e_ but it did not run successfully. I am new to Maven so I don't understand what the problem is except that it's missing Request.js file.

Below is the log.

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Green Navigation
[INFO] Google Frontend
[INFO] Visualization
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Green Navigation 1.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.3:install (default-install) @ GreenNav ---
[INFO] Installing /home/dimple/greennav/pom.xml to /home/dimple/.m2/repository/de/uniluebeck/isp/greennav/GreenNav/1.1/GreenNav-1.1.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Google Frontend 1.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ GoogleFrontend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dimple/greennav/GoogleFrontend/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.4:compile (default-compile) @ GoogleFrontend ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ GoogleFrontend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dimple/greennav/GoogleFrontend/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.4:testCompile (default-testCompile) @ GoogleFrontend ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ GoogleFrontend ---
[INFO] No tests to run.
[INFO] Surefire report directory: /home/dimple/greennav/GoogleFrontend/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- replacer:1.5.2:replace (default) @ GoogleFrontend ---
[ERROR] File '/home/dimple/greennav/GoogleFrontend/src/main/webapp/js/proc/Request.js' does not exist
[INFO] Replacement run on 0 file.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Green Navigation .................................. SUCCESS [0.257s]
[INFO] Google Frontend ................................... FAILURE [0.669s]
[INFO] Visualization ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.051s
[INFO] Finished at: Mon Feb 29 15:06:07 PST 2016
[INFO] Final Memory: 8M/238M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.code.maven-replacer-plugin:replacer:1.5.2:replace (default) on project GoogleFrontend: File '/home/dimple/greennav/GoogleFrontend/src/main/webapp/js/proc/Request.js' does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.code.maven-replacer-plugin:replacer:1.5.2:replace (default) on project GoogleFrontend: File '/home/dimple/greennav/GoogleFrontend/src/main/webapp/js/proc/Request.js' does not exist
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: File '/home/dimple/greennav/GoogleFrontend/src/main/webapp/js/proc/Request.js' does not exist
	at com.google.code.maven_replacer_plugin.ReplacerMojo.execute(ReplacerMojo.java:389)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.io.FileNotFoundException: File '/home/dimple/greennav/GoogleFrontend/src/main/webapp/js/proc/Request.js' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:265)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1457)
	at com.google.code.maven_replacer_plugin.file.FileUtils.readFile(FileUtils.java:32)
	at com.google.code.maven_replacer_plugin.ReplacementProcessor.replace(ReplacementProcessor.java:21)
	at com.google.code.maven_replacer_plugin.ReplacerMojo.replaceContents(ReplacerMojo.java:434)
	at com.google.code.maven_replacer_plugin.ReplacerMojo.execute(ReplacerMojo.java:379)
	... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :GoogleFrontend

**Comment by fabianbormann** [comment]
Hi dimplekp,
 
this is an old greennav version. Sry we forgot to lable it as deprecated please take a look at https://github.com/Greennav/webapp
